// AI Service for Flutter - Calls Gemini Recommendation via Cloud Functions
import 'dart:convert';
import 'package:http/http.dart' as http;

class AiService {
  static const String baseUrl = 'https://asia-southeast1-cocokin-app.cloudfunctions.net';

  // Fetch product recommendations generated by Gemini AI in Cloud Functions
  static Future<List<String>> getRecommendedProductIds(String userId) async {
    try {
      final response = await http.post(
        Uri.parse('$baseUrl/getRecommendations'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'data': {'userId': userId}
        }),
      );
      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final List<dynamic> productIds = data['result']?['productIds'] ?? [];
        return productIds.cast<String>();
      }
      return [];
    } catch (e) {
      print('AI Recommendation Error: $e');
      return [];
    }
  }
}
